### ISSUE TITLE
Need to add new properties

### ISSUE THREAD

**Issue by khider** [mintproject/Mint-ModelCatalog-Ontology#12]
1. Programming language in which the code is written in
2. Software requirements (e.g., Python 3.5. with Pandas package) -> Runtime dependencies
3. For the inputs/outputs: type of input (scalar, grid, time series...)
4. Computational requirements (e.g., number of nodes)
5. Command line execution

**Comment by dgarijo** [comment]
These are all covered by OntoSoft ontology, except the type of input.

**Comment by khider** [comment]
But we still have to gather the information for the models we currently have.

**Comment by khider** [comment]
We also need a property to set the range of acceptable values for a particular variable

**Comment by khider** [comment]
Couple more properties needed for automatic visualization:
1. Datatype (as in string, floats, ints...)
2. Recommended visualization. Value should be string, can be multiple. e.g., bars, mosaic...
